###
#   Database Settings###
##   H2 Settings, local
####
###
upload:
  path: D:/root/Paata/java/Project_Stantion/springMVC/uploads
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/
    expose-request-attributes: true
